import FrequencyResponseProcessor from '../src/frequency-response-processor.js';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Parse REW text file format
 * @param {string} filePath - Path to REW file
 * @returns {Object} - { freqs, magnitude, phase }
 */
function parseREWFile(filePath) {
  const content = readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  const freqs = [];
  const magnitude = [];
  const phase = [];

  for (const line of lines) {
    if (line.startsWith('*') || line.trim() === '') continue;

    const parts = line.trim().split(/\s+/);
    if (parts.length >= 3) {
      freqs.push(Number.parseFloat(parts[0]));
      magnitude.push(Number.parseFloat(parts[1]));
      phase.push(Number.parseFloat(parts[2]));
    }
  }

  return { freqs, magnitude, phase };
}

/**
 * Test calculateMinimumPhase with real REW data
 */
function testCalculateMinimumPhase(createResult = false) {
  console.log('Testing calculateMinimumPhase...\n');

  // Load input data (original measurement)
  const inputPath = join(__dirname, './sw1.txt');
  const input = parseREWFile(inputPath);

  // Load expected output (minimum phase version)
  const expectedPath = join(__dirname, './sw1mp-calculated.txt');
  const expected = parseREWFile(expectedPath);

  console.log(`Loaded ${input.magnitude.length} samples from input`);
  console.log(`Loaded ${expected.phase.length} samples from expected output\n`);

  // Calculate minimum phase from expected magnitude
  const calculated = FrequencyResponseProcessor.calculateMinimumPhase(
    new Float32Array(input.magnitude)
  );

  // Compare results
  let maxError = 0;
  let avgError = 0;
  let errorCount = 0;
  const errors = [];

  for (let i = 0; i < Math.min(calculated.length, expected.phase.length); i++) {
    const error = Math.abs(calculated[i] - expected.phase[i]);
    errors.push(error);
    avgError += error;
    maxError = Math.max(maxError, error);

    if (error > 5) {
      // Tolerance: 5 degrees
      errorCount++;
    }
  }

  avgError /= errors.length;

  // Display results
  console.log('Results:');
  console.log(`  Max error: ${maxError.toFixed(2)}°`);
  console.log(`  Avg error: ${avgError.toFixed(2)}°`);
  console.log(`  Samples with error > 5°: ${errorCount}/${errors.length}`);
  console.log();

  // Show first 10 samples comparison
  console.log('First 10 samples comparison:');
  console.log('Freq(Hz)\tExpected\tCalculated\tError');
  for (let i = 0; i < 10; i++) {
    console.log(
      `${input.freqs[i].toFixed(2)}\t${expected.phase[i].toFixed(2)}\t${calculated[
        i
      ].toFixed(2)}\t${errors[i].toFixed(2)}`
    );
  }
  console.log();

  // Test result
  const tolerance = 10; // 10 degrees tolerance
  const passed = maxError < tolerance && avgError < tolerance / 2;

  console.log(`Test ${passed ? 'PASSED' : 'FAILED'}`);
  console.log(
    `  Max error ${maxError.toFixed(2)}° ${
      maxError < tolerance ? '<' : '>'
    } ${tolerance}° tolerance`
  );
  console.log(
    `  Avg error ${avgError.toFixed(2)}° ${avgError < tolerance / 2 ? '<' : '>'} ${
      tolerance / 2
    }° tolerance`
  );

  // Optionally create result file for REW
  if (createResult) {
    const outputPath = join(__dirname, './sw1mp-calculated.txt');
    createResultFile(input.freqs, input.magnitude, calculated, outputPath);
  }

  return passed;
}

// function to create a result file to be able to import it into REW for visual comparison
function createResultFile(freqs, magnitude, phase, outputPath) {
  const lines = ['* Generated by frequency-response-processor.test.js', ''];
  for (let i = 0; i < freqs.length; i++) {
    lines.push(`${freqs[i]}\t${magnitude[i]}\t${phase[i]}`);
  }
  const content = lines.join('\n');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`Result file created at: ${outputPath}`);
}

// Run test
try {
  // measure time taken
  console.time('Test Duration');
  const startTime = Date.now();
  const result = testCalculateMinimumPhase(false);
  const endTime = Date.now();
  console.timeEnd('Test Duration');
  console.log(`Total time: ${(endTime - startTime) / 1000}s`);

  process.exit(result ? 0 : 1);
} catch (error) {
  console.error('Test failed with error:', error);
  process.exit(1);
}
