/**
 * REW Generic-EQ filter bank helpers extracted from MeasurementItem
 *.
 *
 * [MOTEUR] module: REW exposes a fixed bank of 22 filter slots per
 * measurement; slots 21-22 are reserved for manual (non-auto) filters.
 */

const FILTER_BANK_SIZE = 22;
const AUTO_SLOTS_LIMIT = 20;

function createEmptyFilters() {
  return Array.from({ length: FILTER_BANK_SIZE }, (unused, i) => ({
    index: i + 1,
    type: 'None',
    enabled: true,
    isAuto: true,
  }));
}

/** Number of auto-assignable slots (manual slots 21-22 excluded). */
function countFiltersSlotsAvailable(filters) {
  if (!filters || !Array.isArray(filters)) {
    throw new Error(`Invalid filters: ${filters}`);
  }
  return filters.filter(filter => filter.isAuto === true && filter.index <= AUTO_SLOTS_LIMIT)
    .length;
}

/**
 * Map optimizer output filters onto a REW filter bank.
 * `activeFilters` come from the AutoEQ engine ({filterType, fc, Q, gain}).
 *
 * `reservedIndices` (optional) lists slots that must NOT be assigned nor
 * emitted — slots carrying non-auto filters on the target measurement (the
 * joint per-sub filters, the slot-20 all-pass reservation). The computed
 * filters are packed into the remaining auto slots (1..20); if there are
 * more filters than free slots, the tail is dropped (the AutoEQ engine
 * emits filters in placement-priority order).
 */
function buildPhaseMatchFilters(activeFilters, reservedIndices = []) {
  if (!activeFilters?.length) {
    throw new Error('No filters generated by optimizer');
  }

  const reserved = new Set(reservedIndices);
  const freeIndices = [];
  for (let index = 1; index <= AUTO_SLOTS_LIMIT; index++) {
    if (!reserved.has(index)) freeIndices.push(index);
  }
  if (freeIndices.length === 0) {
    throw new Error('No free filter slots left for the computed filters');
  }

  const bank = new Map(
    createEmptyFilters()
      .filter(slot => !reserved.has(slot.index))
      .map(slot => [slot.index, slot]),
  );

  activeFilters.slice(0, freeIndices.length).forEach((filter, position) => {
    const index = freeIndices[position];
    bank.set(index, {
      index,
      type: filter.filterType === 'PEAKING' ? 'PK' : filter.filterType,
      enabled: true,
      isAuto: true,
      frequency: filter.fc,
      q: filter.Q,
      gaindB: filter.gain,
    });
  });

  return [...bank.values()];
}

/**
 * Repack REW-shaped content filters into the auto slots left free by
 * `reservedIndices`, whatever slots they currently occupy. REW's match
 * target only honours the manual flag on slots that CONTAIN a filter — an
 * empty reservation placeholder does not stop it from claiming the slot —
 * so a shared EQ must be re-laid-out before being distributed to subs whose
 * reserved slots hold their own filters.
 *
 * Returns the full free-slot bank ({ index, type, … } entries, ascending):
 * content filters first, then 'None' empties that clear a previous run's
 * filters. Filters that do not fit are returned in `dropped` (the caller
 * logs them).
 */
function packFiltersIntoFreeSlots(contentFilters, reservedIndices = []) {
  const reserved = new Set(reservedIndices);
  const freeIndices = [];
  for (let index = 1; index <= AUTO_SLOTS_LIMIT; index++) {
    if (!reserved.has(index)) freeIndices.push(index);
  }

  const filters = freeIndices.map((index, position) => {
    const filter = contentFilters[position];
    return filter
      ? { ...filter, index }
      : { index, type: 'None', enabled: true, isAuto: true };
  });

  return { filters, dropped: contentFilters.slice(freeIndices.length) };
}

/** Throws when an optimization frequency range is unusable. */
function validatePhaseMatchRange(freqStart, freqEnd, label = '') {
  if (!Number.isFinite(freqStart) || !Number.isFinite(freqEnd) || freqStart >= freqEnd) {
    throw new RangeError(
      `Invalid optimization range ${freqStart}Hz-${freqEnd}Hz${label ? ` for ${label}` : ''}`,
    );
  }
}

export {
  AUTO_SLOTS_LIMIT,
  FILTER_BANK_SIZE,
  buildPhaseMatchFilters,
  countFiltersSlotsAvailable,
  createEmptyFilters,
  packFiltersIntoFreeSlots,
  validatePhaseMatchRange,
};
