/**
 * REW Generic-EQ filter bank helpers extracted from MeasurementItem
 * (décontamination lot I1 — docs/reverse/03-vm-decontamination.md).
 *
 * [MOTEUR] module: REW exposes a fixed bank of 22 filter slots per
 * measurement; slots 21-22 are reserved for manual (non-auto) filters.
 */

const FILTER_BANK_SIZE = 22;
const AUTO_SLOTS_LIMIT = 20;

function createEmptyFilters() {
  return Array.from({ length: FILTER_BANK_SIZE }, (unused, i) => ({
    index: i + 1,
    type: 'None',
    enabled: true,
    isAuto: true,
  }));
}

/** Number of auto-assignable slots (manual slots 21-22 excluded). */
function countFiltersSlotsAvailable(filters) {
  if (!filters || !Array.isArray(filters)) {
    throw new Error(`Invalid filters: ${filters}`);
  }
  return filters.filter(filter => filter.isAuto === true && filter.index <= AUTO_SLOTS_LIMIT)
    .length;
}

/**
 * Map optimizer output filters onto a fresh REW filter bank.
 * `activeFilters` come from the AutoEQ engine ({filterType, fc, Q, gain}).
 */
function buildPhaseMatchFilters(activeFilters) {
  if (!activeFilters?.length) {
    throw new Error('No filters generated by optimizer');
  }

  const filters = createEmptyFilters();

  activeFilters.forEach((filter, index) => {
    filters[index] = {
      index: index + 1,
      type: filter.filterType === 'PEAKING' ? 'PK' : filter.filterType,
      enabled: true,
      isAuto: true,
      frequency: filter.fc,
      q: filter.Q,
      gaindB: filter.gain,
    };
  });

  return filters;
}

/** Throws when an optimization frequency range is unusable. */
function validatePhaseMatchRange(freqStart, freqEnd, label = '') {
  if (!Number.isFinite(freqStart) || !Number.isFinite(freqEnd) || freqStart >= freqEnd) {
    throw new RangeError(
      `Invalid optimization range ${freqStart}Hz-${freqEnd}Hz${label ? ` for ${label}` : ''}`,
    );
  }
}

export {
  AUTO_SLOTS_LIMIT,
  FILTER_BANK_SIZE,
  buildPhaseMatchFilters,
  countFiltersSlotsAvailable,
  createEmptyFilters,
  validatePhaseMatchRange,
};
